name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip1
      - run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: wasm-plugin
          path: target/wasm32-wasip1/release/zellij-pick-vim-target.wasm

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: wasm-plugin
      - run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - run: gh release create -t "Release ${{ env.TAG }}" "${{ env.TAG }}" zellij-pick-vim-target.wasm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
